path_to_jsonl :           # Path to the training data in JSONL format
data_output_directory :   # Directory where the processed data will be saved
data_name :               # Name of the dataset   
use_normalize :           # Whether to normalize the data
path_to_model :           # Path to the pre-trained model
finetuned_model_output :  # Directory where the finetuned model will be saved
training_config_file :    # Path to the training configuration file